# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2
  slack: circleci/slack@4.10.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1
jobs:
  build-job:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: npm run unit
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
  deploy-job:
        docker:
          - image: cimg/base:stable
        steps:
          - node/install
          - restore_cache:
              keys:
                - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
          - run:
              name: show directory 
              command: pwd
          - run:
              name: Install Firebase
              command: npm install --save-dev firebase-tools
          - run:
              name: look in directory
              command: ls -ltr
          - run:
              name: Deploy Master to Firebase
              command: npm run firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN 
          - notify_slack_error
          - notify_slack_pass


workflows:
  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main
